ab08dd98c1332b417a79cfc294d87f8b 44 SAMSUNG\-SGH\-D[\d][\d][\d]\/[\d]\.[\d]\/WAP[\d]\.[\d] .*\/.* UP\.Browser\/[\d]\.[\d].*
ab25030e9d490a584d547b668c07e2de 23 SIE\-S[\d][\d]\/.* UP\.Browser\/[\d]\.[\d].*
ab2f833a4b659751192820dcdba7a0a1 25 SIE\-C[\d][\d]\/[\d]. UP\.Browser\/[\d]\.[\d].*
ab737f7beafac4cfdbdcacb26f2dcf38 29 NOKIA\-RH\-[\d][\d]\/V .* UP\.Browser\/[\d]\.[\d].*
ab7497c34624de9dfd6c40ce6d35a9d2 53 Amoi\-V[\d][\d][\d]\/Plat\-EMP\/WAP[\d]\.[\d]\/MIDP[\d]\.[\d]\/CLDC[\d]\.[\d] UP\.Link\/[\d]\.[\d].*
abaecf8ca3f98dc13eeecbac263cd3ed 24 BIRD SC[\d][\d] UP\.Browser\/[\d]\.[\d].*
abca60943dd02f25d43e3658705cc1ae 17 DoCoMo\/[\d]\.[\d]\/N[\d][\d][\d]i\/.*
abe919181f2e646452637467de2bfe44 19 Coursera\-Mobile.[\d]\.[\d].*
abe919181f2e646452637467de2bfe44 15 Coursera\-Mobile.*
abefca8109e4ef0624ce7c328bb46cc5 48 SAMSUNG\-GT\-C[\d][\d][\d][\d] Opera\/.*\(J[\d]ME\/MIDP.*Opera Mini\/[\d]\.[\d].*\).*
abf90b3ea01b742778b0aadb2f620349 8 LeechGet.*
abf9f9798e3c71b9e841264a4e6d0fcd 49 K\-Meleon\/[\d][\d]\.[\d] \(.*Windows NT [\d]\.[\d].*\) Gecko\/.* Mozilla\/[\d]\.[\d]
